version: "2"

services:
  server:
    container_name: sterling-test-app-server
    restart: always
    build: .
    ports:
      - "3000:80"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
