version: "2"

services:
  server:
    container_name: sterling-test-app-server
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - "./server:/usr/src/sterling_app"
      - "/usr/src/Sterling_app/node_modules"
    links:
      - mongo
  # mongo:
  #   container_name: mongo_sterling
  #   image: mongo
  #   ports:
  #     - "27017:27017"
